### ISSUE TITLE
What is the origin of the Hyahatiph Labs logo?

### ISSUE THREAD

**Issue by pinheadmz** [hyahatiph-labs/infosec#6]
Greetings from https://github.com/handshake-org! We have a very similar logo, I think it was designed for our project by IDEO back in 2018.

**Comment by reemuru** [comment]
> Greetings from https://github.com/handshake-org! We have a very similar logo, I think it was designed for our project by IDEO back in 2018.

@pinheadmz  ah yeah, apologies I thought it came from a clip art library. It is being updated now. Not being used anywhere else for Hyahatiph Labs afaik. Will double check and update if necessary.

**Comment by pinheadmz** [comment]
Thanks good luck! I heard about you from /r/monero ;-)
